=== ENG-AhmedSameh/ITI-Labs/XML/lab3/out/production/lab3/library/librarySchema.xsd
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://ahmedsameh_lab2_task5"
        xmlns="https://ahmedsameh_lab2_task5"
        elementFormDefault="qualified">
    <xs:element name="library">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation >
                    this chapter is Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
                </xs:documentation>
            </xs:annotation>
            <xs:sequence>

                <xs:element name="location">
                    <xs:complexType>
                        <xs:group ref="locationGroup"/>
                    </xs:complexType>
                </xs:element>


                <xs:element name="librarian">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="personInfo">
                                <xs:attribute name="id">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:int">
                                            <xs:minExclusive value="1000"/>
                                            <xs:maxExclusive value="2000"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:complexContent>

                    </xs:complexType>
                </xs:element>

                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element ref="title"/>

                                        <xs:element name="ISBN">
                                            <xs:complexType>

                                                <xs:simpleContent>
<!--                                                    <xs:restriction base="xs:string">-->
<!--                                                        <xs:length value="13"/>-->
<!--                                                    </xs:restriction>-->
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="distribution" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>

                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="author">
                                            <xs:complexType>
                                                <xs:attribute name="name"/>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name = "preface" type="xs:string"/>
                                        <xs:element name="sections">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name = "chapter" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element ref="title"/>
                                                                <xs:element name="content" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute name="desc" type="xs:string"/>

        </xs:complexType>
    </xs:element>

    <xs:group name="locationGroup">
        <xs:sequence>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="district" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="personInfo">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="title" type="xs:string"/>

</xs:schema>

=== ENG-AhmedSameh/ITI-Labs/XML/lab2/src/Task 5/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<library desc = "This is the library of the institue"
    xmlns="https://ahmedsameh_lab2_task5"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://ahmedsameh_lab2_task5 librarySchema.xsd">

    <location>
        <city>cairo</city>
        <district>smart village</district>
    </location>
    <librarian id="1530">
        <firstName>Ahmed</firstName>
        <lastName>Sameh</lastName>
    </librarian>

    <books>
        <book>
            <title>clean code</title>
            <ISBN distribution="global">12345Ahmd13</ISBN>
            <author name ="Craftsman"/>
            <preface>
                <![CDATA["This book is for < boys & girls > 15 years]]>
            </preface>

            <sections>
                <chapter>
                    <title>functions</title>
                    <content>hello world</content>
                </chapter>
                <chapter>
                    <title>variables</title>
                    <content>hello world</content>
                </chapter>
            </sections>
        </book>

        <book>
            <title>OOP</title>
            <ISBN distribution="global">12345Ahmd13</ISBN>
            <author name ="AhmedSameh"/>
            <preface>
                <![CDATA["This book is for cracking interviews]]>
            </preface>

            <sections>
                <chapter>
                    <title>inheritance</title>
                    <content>hello world</content>
                </chapter>
                <chapter>
                    <title>polymorphism</title>
                    <content>hello world</content>
                </chapter>
            </sections>
        </book>

    </books>
</library>
