=== ENG-AhmedSameh/ITI-Labs/XML/lab1/src/libraryDTD.dtd
<!ELEMENT library (location, librarian,books)>
<!ELEMENT location (city, district)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT district (#PCDATA)>
<!ELEMENT librarian (firstName,lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT books (book+)>
<!ELEMENT book (title,ISBN,author,preface,sections)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT author EMPTY>
<!ELEMENT preface (#PCDATA)>
<!ELEMENT sections (chapter+)>
<!ELEMENT chapter (title,content)>

<!ELEMENT content (#PCDATA)>

<!ATTLIST library desc CDATA #REQUIRED>
<!ATTLIST librarian id CDATA>
<!ATTLIST author name CDATA>

=== ENG-AhmedSameh/ITI-Labs/XML/lab1/src/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library SYSTEM "libraryDTD.dtd">
<library desc = "This is the library of the institue">
    <location>
        <city>cairo</city>
        <district>smart village</district>
    </location>
    <librarian id="AH_SA_1510">
        <firstName>Ahmed</firstName>
        <lastName>Sameh</lastName>
    </librarian>

    <books>
        <book>
            <title>clean code</title>
            <ISBN>3256378743764</ISBN>
            <author name ="AhmedSameh"/>
            <preface>
               <![CDATA["This book is for < boys & girls > 15 years]]>
            </preface>

            <sections>
                <chapter>
                    <title>functions</title>
                    <content>hello world</content>
                </chapter>
                <chapter>
                    <title>variables</title>
                    <content>hello world</content>
                </chapter>
            </sections>
        </book>

    </books>
</library>
