=== ENG-AhmedSameh/ITI-Labs/XML/lab2/src/Task1/BookStoreSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://ahmedsameh_lab2_task1"
        xmlns="https://ahmedsameh_lab2_task1"
        elementFormDefault="qualified">
    <xs:element name="BookStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="date" type="xs:date"/>
                            <xs:element name="ISBN" type="xs:int"/>
                            <xs:element name="publisher" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== ENG-AhmedSameh/ITI-Labs/XML/lab2/src/Task1/BookStore.xml
<?xml version="1.0" encoding="UTF-8" ?>
<BookStore
        xmlns="https://ahmedsameh_lab2_task1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://ahmedsameh_lab2_task1 BookStoreSchema.xsd"
>
    <Book>
        <title>Clean code</title>
        <author>craftsman</author>
        <date>1999-10-15</date>
        <ISBN>12345</ISBN>
        <publisher>Dar misr</publisher>
    </Book>
    <Book>
        <title>spring starts here</title>
        <author>ahmed sameh</author>
        <date>2025-01-01</date>
        <ISBN>1510</ISBN>
        <publisher>Dar misr</publisher>
    </Book>
</BookStore>
