=== ENG-AhmedSameh/ITI-Labs/XML/lab2/src/Task 2/BookStoreSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://ahmedsameh_lab2_task2"
        xmlns="https://ahmedsameh_lab2_task2"
        elementFormDefault="qualified">
    <xs:element name="bookStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>

                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                        </xs:sequence>

                        <xs:attribute name="category" default="fiction">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="science"/>
                                    <xs:enumeration value="fiction"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="inStock" default="false" type="xs:boolean"/>
<!--                            <xs:simpleType>-->
<!--                                <xs:restriction base="xs:string">-->
<!--                                    <xs:enumeration value="true"/>-->
<!--                                    <xs:enumeration value="false"/>-->
<!--                                </xs:restriction>-->
<!--                            </xs:simpleType>-->
<!--                        </xs:attribute>-->

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== ENG-AhmedSameh/ITI-Labs/XML/lab2/src/Task 2/BookStore.xml
<?xml version="1.0" encoding="UTF-8" ?>
<bookStore
        xmlns="https://ahmedsameh_lab2_task2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://ahmedsameh_lab2_task2 BookStoreSchema.xsd"
>
    <book category="science" inStock="true">
        <title>Clean code</title>
        <author>craftsman</author>
    </book>
    <book category="fiction">
        <title>spring starts here</title>
        <author>ahmed sameh</author>
    </book>
    <book>
        <title>OOP head first</title>
        <author>nahah nshsah</author>
    </book>
</bookStore>
